### ISSUE TITLE
user flags example does not exemplify how to use flags.cmake

### ISSUE THREAD

**Issue by kybr** [AlloSphere-Research-Group/allolib#11]
`examples/user_flags/` should show how to use flags.cmake to cooperate with the build system to connect with some external system (e.g., Leap Motion SDK C++ API, MySQL C API, OpenCV C++ API). Instead, it presents [code that does not even try to use an external system](https://github.com/AlloSphere-Research-Group/allolib/blob/master/examples/user_flags/main.cpp) and a [flags.cmake file that does not show how one might practically use a flags.cmake](https://github.com/AlloSphere-Research-Group/allolib/blob/master/examples/user_flags/flags.cmake) file.

The flags.cmake file shows that I can (and should?) set 4 variables: app_include_dirs, app_link_libs, app_definitions, and app_compile_flags. Are these the only variables I can set? What are some *examples* of how I might set them for a given external system? What useful variables do I have access to in this flags.cmake? For instance, do I know the project root folder path? Can I use relative paths to set these variables? Relative to where? (Again, where's the project root?)

**Comment by mantaraya36** [comment]
Fixed cbcea568a16616a3d4fa1275786df7ef68affe63 and fe1eec2243b39a2e6c2b7000d4e51df463b235b2
