### ISSUE TITLE
`examples/ui/dialog.cpp` | unexpected behaviour and crash

### ISSUE THREAD

**Issue by kybr** [AlloSphere-Research-Group/allolib#12]
Judging just from the name, `dialog.cpp` (and `al::Dialog`), I expect this example and this class to open an OS-native window in order to ask something of the user (e.g., select a file, select an output folder, etc.). Instead, a second window appears with a flashing background and an ImGui debug window within it---How is that a "dialog"? What's more, when I trigger the "dialog" a second time, the example crashes. ?

I'm using macOS 10.14.2 Beta (18C31g).

This example does not have any comments or documentation. What is it supposed to show? How is an `al::Dialog` supposed to be used? What's it for?

**Comment by mantaraya36** [comment]
Made mutiple fixes and there is a now a basic working dialog that opens a new window. Only basic questions and messages for now but could be expanded to support input. Currently crashes if more than one dialog is opened, but works OK for single dialog. ee6a31deb4034706ef35d218cdc3c4493cc21209
