### ISSUE TITLE
slash handling in the parameter class

### ISSUE THREAD

**Issue by kybr** [AlloSphere-Research-Group/allolib#15]
https://github.com/AlloSphere-Research-Group/allolib/blob/c035664e77acaf4244c94c3f11d8b11c8b66c490/src/util/ui/al_Parameter.cpp#L107

What's wrong with letting the user manage all the slashes? Why try to figure out what they might have meant and correcting their (might be) errors? If this is the way that Parameter is going to work, then the class needs to loudly announce to the user "by using this class you are buying in to our ad-hoc OSC++ schema; you don't get to manage shashes."

Personally, I would much rather manage slashes myself.

**Comment by mantaraya36** [comment]
Seems fixed in https://github.com/AlloSphere-Research-Group/allolib/commit/2ff33916df1339656df0d173900b1f4f96f16638
