### ISSUE TITLE
P

### ISSUE THREAD

**Issue by kybr** [AlloSphere-Research-Group/allolib#16]
https://github.com/AlloSphere-Research-Group/allolib/blob/6eb879be455a16225763aa22fcadd157cbd69d19/examples/graphics/light.cpp#L59

We really can't afford the extra characters it takes to spell out "projection" or "projectionMatrix"? MV instead of "modelViewMatrix"? You only have to type the long names once. forever after, you only type mod[TAB] or pro[TAB]. That's the case if you use a decent code editor. The verbosity is valuable for people who are learning. Students that look into the guts of this stuff, I'd like them to be able to have enough to google what they find.

**Comment by younkhg** [comment]
You are right. We should change that. I'll work on it.

It'll break previous projects that use custom shaders. But it's better to break fewer projects (probably only ARG projects) now.

**Comment by younkhg** [comment]
Commit 1dc669d808a2c835dd80b0d66a8c32a89e9d2fca pushed.
@mantaraya36 can you try updating shaders in other ARG projects to use these names?
