### ISSUE TITLE
instance_drawing.cpp improvements

### ISSUE THREAD

**Issue by kybr** [AlloSphere-Research-Group/allolib#19]
I'm talking about this example:

[examples/graphics/instance_drawing.cpp](https://github.com/AlloSphere-Research-Group/allolib/blob/master/examples/graphics/instance_drawing.cpp)

[Float4](https://github.com/AlloSphere-Research-Group/allolib/blob/8e9a133f31eac4257cefda15491e181379b7552a/examples/graphics/instance_drawing.cpp#L61) is just a `Vec4f`, so use a `Vec4f`. Except the fourth element [is always 1](https://github.com/AlloSphere-Research-Group/allolib/blob/8e9a133f31eac4257cefda15491e181379b7552a/examples/graphics/instance_drawing.cpp#L144), so use `Vec3f` instead, unless [this operation](https://github.com/AlloSphere-Research-Group/allolib/blob/8e9a133f31eac4257cefda15491e181379b7552a/examples/graphics/instance_drawing.cpp#L29) is much more efficent than `vec4 p = vec4(scale * position + offset, 1.0);` where offset is a `vec3`.

This example does not offer any context beyond the name of the file. Please list a goal (or a description), a set of topics/tags/keywords, an author, and a date. Like [this](https://github.com/AlloSphere-Research-Group/allolib/blob/8e9a133f31eac4257cefda15491e181379b7552a/examples/graphics/point-cloud-geometry-shader-texture-sprite.cpp#L1).

**Comment by younkhg** [comment]
Using Float4 was to show that any user data struct can be used. I'll add comment about it.
Changing to vec3 seems correct.

pushed f654d2202f8fed8ed225fe135e3d1e94da111613

**Comment by mantaraya36** [comment]
I believe the issue has been solved by f654d22
