### ISSUE TITLE
Distributed/DynamicScene | communication between voice and app

### ISSUE THREAD

**Issue by kybr** [AlloSphere-Research-Group/allolib#23]
i'm looking at [dynamic_scene.cpp] and [distributed_scene.cpp] because i need to spatialize some sounds and AudioScene is broken and deprecated. these classes seem to be awesomely synthesiser-oriented, but my application does not quite fit that use-case.

- my voices don't move after they are placed; only the listener moves
- my voices are always on while the app is running; no "notes" come and go
- my voices use gam::SamplePlayer which allocates memory on load; this load should happen before the audio callback
- each of my voices loads its own, specific sound file; voices are not fungible[1]
- each of my voices needs to be drawn using a central, reused graphics resource rather than using voice-local member variables[2]

[1] i need a way to communicate between voice and app. i see that the way to do this is with parameters. i could do something like this, but i don't like it:

```c++
gam::SamplePlayer samplePlayer[N]; // global
...
struct SimpleVoice : PositionedVoice {
  ParameterInt whichSound {"whichSound"};
...
 virtual void onProcess(AudioIOData& io) override {
        while(io()){
            io.out(0) = soundFile[whichSound]();
        }
    }
...
// later in the app...
           auto whichSound = std::vector<int>{0};
           freeVoice->setParamFields(whichSound);
```

[2] this means that in the main apps onDraw, i would like to iterate through each active voice, querying its pose:

```c++
Mesh mesh;
Texture texture;
...
virtual void onDraw(Graphics& g) override {
  ...
  texture.bind();
  for (auto& v : scene.activeVoices()) {
    g.pushMatrix();
    g.translate(v.pos());
    g.rotate(v.quat());
    g.draw(mesh);
    g.popMatrix();
  }
  texture.unbind();
}
...

```

is there something like `scene.activeVoices()`??

[dynamic_scene.cpp]: https://github.com/AlloSphere-Research-Group/allolib/blob/master/examples/ui/dynamic_scene.cpp
[distributed_scene.cpp]: https://github.com/AlloSphere-Research-Group/allolib/blob/master/examples/ui/distributed_scene.cpp

**Comment by kybr** [comment]
i have something working: https://github.com/yujnkm/MAT201B-yujnkm/blob/master/FinalProject/sketch-eyes-sound-background.cpp

**Comment by mantaraya36** [comment]
Thanks. Based on your example, I have written this new dynamic scene example to show userData() and always on voices
https://github.com/AlloSphere-Research-Group/allolib/blob/aa83098634da6c164e4cd80251c8edde87d2310d/examples/ui/dynamic_scene2.cpp
