### ISSUE TITLE
need check on al::Speaker's ctor signature

### ISSUE THREAD

**Issue by younkhg** [AlloSphere-Research-Group/allolib#28]
https://github.com/AlloSphere-Research-Group/allolib/blob/15ed8c56d2ad2b2b0157673c1134d3bea29ae3eb/include/al/sphere/al_AlloSphereSpeakerLayout.hpp#L9-L23

https://github.com/AlloSphere-Research-Group/allolib/blob/15ed8c56d2ad2b2b0157673c1134d3bea29ae3eb/include/al/sound/al_Speaker.hpp#L51-L73

it seems that ctor signature of al::Speaker and its use case in AlloSphereSpeakerLayout does not match.

**Comment by mantaraya36** [comment]
Fixed 3929ffc755a6d869dea36c5c3fd5e704c902b5ad
