### ISSUE TITLE
examples/spatial/hashSpace.cpp crashes

### ISSUE THREAD

**Issue by kybr** [AlloSphere-Research-Group/allolib#33]
This example segfaults on macOS, Linux and Windows.

**Comment by mantaraya36** [comment]
Fixed crashing from App::title() e1f9499e2408d369dccde0db127ad038ec4b0a36
Still crashing on usage of HasSpace::Query. Can you take a look, I am unsure how this works...

**Comment by mantaraya36** [comment]
Believe fixed 472a2d3944e18343acc18a8123e243aeb3af8e85.

There could be performance improvements to be done, but it appears to be working correctly.
