### ISSUE TITLE
Update the portaudio backend; Tiny changes! (at least on macOS)

### ISSUE THREAD

**Issue by kybr** [AlloSphere-Research-Group/allolib#42]
1) Make `int framesPerBuffer` read `unsigned int framesPerBuffer` to match the rtaudio implementation: https://github.com/AlloSphere-Research-Group/allolib/blob/c0474d8b01deff41c0cc1c839f87f808eac74d44/src/io/al_AudioIO.cpp#L289
2) Make the build system link to portaudio rather than rtaudio: https://github.com/AlloSphere-Research-Group/allolib/blob/c0474d8b01deff41c0cc1c839f87f808eac74d44/CMakeLists.txt#L280

**Comment by kybr** [comment]
Why bother maintaining the portaudio backend?

portaudio and rtaudio are not perfect. They each may have issues that come up from time to time. The ability to swap them out is a tool when troubleshooting; One may not have the issue that the other has. I'm sure there are other good reasons, but that's the one I'm arguing.

**Comment by mantaraya36** [comment]
Thanks, can you test this pull request? #43

**Comment by mantaraya36** [comment]
Assumed to be working.
