### ISSUE TITLE
-v flag does not help in run.sh script

### ISSUE THREAD

**Issue by kybr** [AlloSphere-Research-Group/allolib#5]
To support debugging we need to see the compile and linker lines. However, `./run.sh -v` does not show these. What is `-v` for if not to show this information?

**Comment by mantaraya36** [comment]
Added info to script. No arguments or -h display usage #

**Comment by kybr** [comment]
This did not address the issue I raised. I don't know how other developers are working, but I need to see the compiler and linker lines. `./run.sh -v` does not help with this, even after the update above. Please see [Using CMake with GNU Make: How can I see the exact commands?](https://stackoverflow.com/questions/2670121/using-cmake-with-gnu-make-how-can-i-see-the-exact-commands). I've fixed this here:

https://github.com/AlloSphere-Research-Group/allolib/commit/66c8dd4d9bc26d8759f8830e1718e6e6e273146b

**Comment by mantaraya36** [comment]
Thanks!
