### ISSUE TITLE
graphics examples open a black window until the window is moved or full-screened on macOS 10.14 

### ISSUE THREAD

**Issue by kybr** [AlloSphere-Research-Group/allolib#9]

**Comment by mantaraya36** [comment]
Can't reproduce on OS X 10.13.4. Do all graphic example behave like this? Is this only on 10.14?

**Comment by kybr** [comment]
Yes. Yes. I don't consider this a high-priority issue because 10.14 is beta. However, it is something to be aware of because changes are coming to macOS graphics.

**Comment by kybr** [comment]
also, this might be a GLFW-level issue.

**Comment by mantaraya36** [comment]
I haven't heard about this problem for a while. I assume it has been fixed.
